[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/"
  to = "/remake-v2/"
  status = 302
  force = true

[[redirects]]
  from = "/remake-v2"
  to = "/remake-v2/"
  status = 301
  force = true

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/remake-v2/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/base/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sections/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/showcase-assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
